export const registerInitialValues = {
    name: "",
    email: "",
    password: "",
};
export const registerFormFields = [
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "name",
        label: "Enter your name",
        size: "medium",
        name: "name",
        type: "name",
        variant: "outlined",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "email",
        label: "Enter your email",
        size: "medium",
        name: "email",
        type: "email",
        variant: "outlined",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "password",
        label: "Password",
        size: "medium",
        name: "password",
        type: "password",
        variant: "outlined",
        color: "primary",
    },
    {
        field: "button",
        variant: "solid",
        color: "#383ab6",
        id: "login",
        fullWidth: "100%",
        type: "submit",
        size: "lg",
        label: "Sign up",
    },
];
