import { BsCalendar3 } from "react-icons/bs";
import { FaUserClock } from "react-icons/fa";
import { FiUsers } from "react-icons/fi";
import { ImProfile } from "react-icons/im";
import { LuLayoutDashboard } from "react-icons/lu";
import { MdOutlineAccountBalance } from "react-icons/md";
import { TbPointerDollar } from "react-icons/tb";

export const ROUTE_PATH = {
    HOME: "/home",
    PROFILE: "/profile",
    USERS: "/users",
    BANK: "/bank-detail",
    PAYROLL: "/payroll-detail",
    ATTENDANCE: "/attendance-detail",
    LEAVE: "/leave-detail",
};
export const TOAST = {
    SUCCESS: {
        title: "Data Updated Successfully",
        status: "success",
        isClosable: true,
    },
    ERROR: {
        title: "Sorry! Please try again.",
        status: "error",
        isClosable: true,
    },
};
export const MENU_LIST = [
    {
        path: "/",
        name: "Home",
        icon: LuLayoutDashboard,
    },
    {
        path: ROUTE_PATH.PROFILE,
        name: "Profile",
        icon: ImProfile,
    },
    {
        path: ROUTE_PATH.USERS,
        name: "Users",
        icon: FiUsers,
    },
    {
        path: ROUTE_PATH.BANK,
        name: "Bank",
        icon: MdOutlineAccountBalance,
    },
    {
        path: ROUTE_PATH.PAYROLL,
        name: "Payroll",
        icon: TbPointerDollar,
    },
    {
        path: ROUTE_PATH.LEAVE,
        name: "Leave",
        icon: BsCalendar3,
    },
    {
        path: ROUTE_PATH.ATTENDANCE,
        name: "Attendance",
        icon: FaUserClock,
    },
];
export const USER_ROLE = {
    EMPLOYEE: "Employee",
    MANAGER: "Super Manager",
    HR: "HR/Manager",
    ADMIN: "Administrator",
};
export const LEAVE_TYPES = [
    "Sick leave",
    "Casual leave",
    "Public holiday",
    "Religious holiday",
    "Maternity leave",
    "Paternity leave",
    "Bereavement leave",
    "Compensatory leave",
    "Sabbatical leave",
    "Unpaid leave",
];
export const loginInitialValues = {
    email: "",
    password: "",
};
export const LABELS = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
];
export const notifications = [
    {
        sticky: true,
        severity: "success",
        detail: "Reminder: Meeting tomorrow at 10:00 AM",
    },
    {
        sticky: true,
        severity: "info",
        detail: "Upcoming Event: Payroll cutoff date on July 15th at 7:00 PM",
    },
    {
        sticky: true,
        severity: "success",
        detail: "Important Deadline: Project submission due on September 20th",
    },
    {
        sticky: true,
        severity: "info",
        detail: "Special Event: Company retreat on November 12th-15th",
    },
    {
        sticky: true,
        severity: "warn",
        detail: "Exciting News: New product launch on February 15th",
    },
    {
        sticky: true,
        severity: "error",
        detail: "Mark your calendar: Holiday party on December 23rd",
    },
];
export const loginFormFields = [
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "email",
        label: "Email",
        name: "email",
        type: "email",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "password",
        label: "Password",
        name: "password",
        type: "password",
        variant: "solid",
        color: "primary",
    },
    {
        field: "link",
        id: "link",
        variant: "text",
        path: "/forgot-password",
        label: "Forgot password",
    },
    {
        field: "button",
        variant: "primary",
        id: "login",
        type: "submit",
        label: "Sign in",
        size: "sm",
    },
];
export const signUpInitialValues = {
    firstName: "",
    middleName: "",
    lastName: "",
    email: "",
    password: "",
    role: "",
    dateOfJoining: "",
    phoneNumber: "",
    streetNumber: "",
    city: "",
    postalCode: "",
    state: "",
    country: "",
};
export const signUpFormFields = [
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "firstName",
        isRequired: true,
        label: "First Name",
        size: "medium",
        name: "firstName",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "middleName",
        label: "Middle Name",
        size: "medium",
        name: "middleName",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        isRequired: true,
        id: "lastName",
        label: "Last Name",
        size: "medium",
        name: "lastName",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        isRequired: true,
        id: "email",
        label: "Email Address",
        size: "medium",
        name: "email",
        type: "email",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "password",
        label: "Password",
        size: "medium",
        isRequired: true,
        name: "password",
        type: "password",
        variant: "solid",
        color: "primary",
    },
    {
        field: "select",
        margin: "dense",
        fullWidth: true,
        id: "role",
        label: "Role",
        size: "medium",
        name: "role",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "date",
        margin: "dense",
        fullWidth: true,
        id: "dateOfJoining",
        label: "Date of Joining",
        size: "medium",
        name: "dateOfJoining",
        type: "date",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "phoneNumber",
        label: "Phone Number",
        size: "medium",
        name: "phoneNumber",
        type: "tel",
        variant: "solid",
        color: "primary",
    },
    {
        field: "country",
        margin: "dense",
        fullWidth: true,
        id: "country",
        label: "Country",
        size: "medium",
        name: "country",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "state",
        margin: "dense",
        fullWidth: true,
        id: "state",
        label: "State",
        size: "medium",
        name: "state",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "city",
        margin: "dense",
        fullWidth: true,
        id: "city",
        label: "City",
        size: "medium",
        name: "city",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "streetNumber",
        label: "Street Number",
        size: "medium",
        name: "streetNumber",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "postalCode",
        label: "Postal Code",
        size: "medium",
        name: "postalCode",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "button",
        variant: "primary",
        id: "register",
        fullWidth: "100%",
        type: "submit",
        label: "Create account",
    },
];
export const userPaymentInitialValues = {
    annualSalary: "",
};
export const userPaymentFormFields = [
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "annualSalary",
        label: "Annual Salary  ",
        size: "medium",
        name: "annualSalary",
        type: "number",
        variant: "solid",
        color: "primary",
    },
    {
        field: "button",
        variant: "solid",
        color: "#383ab6",
        id: "login",
        type: "submit",
        size: "lg",
        label: "Add",
    },
];
export const resetPasswordInitialValues = {
    email: "",
};
export const resetPasswordFormFields = [
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "email",
        size: "medium",
        label: "",
        name: "email",
        type: "email",
        variant: "outlined",
        color: "primary",
        placeholder: "Enter your email",
    },
    {
        field: "button",
        variant: "primary",
        id: "login",
        fullWidth: "100%",
        type: "submit",
        size: "md",
        label: "Continue with email",
    },
];
export const otpPasswordFormFields = [
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "firstChar",
        size: "medium",
        name: "firstChar",
        type: "text",
        variant: "outlined",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "secondChar",
        size: "medium",
        name: "secondChar",
        type: "text",
        variant: "outlined",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "thirdChar",
        size: "medium",
        name: "thirdChar",
        type: "text",
        variant: "outlined",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "fourthChar",
        size: "medium",
        name: "fourthChar",
        type: "text",
        variant: "outlined",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "fifthChar",
        size: "medium",
        name: "fifthChar",
        type: "text",
        variant: "outlined",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "sixthChar",
        size: "medium",
        name: "sixthChar",
        type: "text",
        variant: "outlined",
        color: "primary",
    },
    {
        field: "button",
        variant: "contained",
        color: "primary",
        id: "verify",
        fullWidth: true,
        type: "submit",
        size: "large",
        label: "Verify Email",
        style: { mt: 1, mb: "2em" },
    },
];
