export const loginInitialValues = {
    email: "",
    password: "",
};
export const loginFormFields = [
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "email",
        label: "Email",
        name: "email",
        type: "email",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "password",
        label: "Password",
        name: "password",
        type: "password",
        variant: "solid",
        color: "primary",
    },
    {
        field: "link",
        id: "link",
        variant: "text",
        path: "/forgot-password",
        label: "Forgot password",
    },
    {
        field: "button",
        variant: "primary",
        id: "login",
        type: "submit",
        label: "Sign in",
        size: "sm",
    },
];
export const userInitialValues = {
    firstName: "",
    middleName: "",
    lastName: "",
    email: "",
    password: "",
    role: "",
    dateOfJoining: "",
    phoneNumber: "",
    streetNumber: "",
    city: "",
    postalCode: "",
    state: "",
    country: "",
};
export const userPaymentInitialValues = {
    annualSalary: "",
};
export const userPaymentFormFields = [
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "annualSalary",
        label: "Annual Salary  ",
        size: "medium",
        name: "annualSalary",
        type: "number",
        variant: "solid",
        color: "primary",
    },
    {
        field: "button",
        variant: "solid",
        color: "#383ab6",
        id: "login",
        type: "submit",
        size: "lg",
        label: "Add",
    },
];
export const userFormFields = [
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "firstName",
        label: "First Name",
        size: "medium",
        name: "firstName",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "middleName",
        label: "Middle Name",
        size: "medium",
        name: "middleName",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "lastName",
        label: "Last Name",
        size: "medium",
        name: "lastName",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "email",
        label: "Email Address",
        size: "medium",
        name: "email",
        type: "email",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "password",
        label: "Password",
        size: "medium",
        name: "password",
        type: "password",
        variant: "solid",
        color: "primary",
    },
    {
        field: "select",
        margin: "dense",
        fullWidth: true,
        id: "role",
        label: "Role",
        size: "medium",
        name: "role",
        type: "select",
        variant: "solid",
        color: "primary",
    },
    {
        field: "date",
        margin: "dense",
        fullWidth: true,
        id: "dateOfJoining",
        label: "Date of Joining",
        size: "medium",
        name: "dateOfJoining",
        type: "date",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "phoneNumber",
        label: "Phone Number",
        size: "medium",
        name: "phoneNumber",
        type: "number",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "streetNumber",
        label: "Street Number",
        size: "medium",
        name: "streetNumber",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "city",
        label: "City",
        size: "medium",
        name: "city",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "postalCode",
        label: "Postal Code",
        size: "medium",
        name: "postalCode",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "state",
        label: "State",
        size: "medium",
        name: "state",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "textField",
        margin: "dense",
        fullWidth: true,
        id: "country",
        label: "Country",
        size: "medium",
        name: "country",
        type: "text",
        variant: "solid",
        color: "primary",
    },
    {
        field: "button",
        variant: "solid",
        color: "#383ab6",
        id: "register",
        fullWidth: "100%",
        type: "submit",
        size: "lg",
        label: "Sign up",
    },
];
